"""test

Revision ID: cbbbca238649
Revises: fba65b98ad93
Create Date: 2025-03-17 08:55:57.421977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbbbca238649'
down_revision: Union[str, None] = 'fba65b98ad93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('name', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'phone')
    op.drop_column('patients', 'name')
    # ### end Alembic commands ###
